### ISSUE TITLE
Too many open connections leads to crash

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#797]
If you open too many connections to RCT then it will crash.  Here is the stack:

```
Program received signal SIGINT, Interrupt.
[Switching to Thread 536905200]
0x0800efbc in vPortFree (pv=pv@entry=0x20008af8) at FreeRTOS/Source/portable/MemMang/heap_4.c:268
268                     configASSERT( ( pxLink->xBlockSize & xBlockAllocatedBit ) != 0 );
(gdb) thread 2
[Switching to thread 2 (Thread 536905200)]
#0  0x0800efbc in vPortFree (pv=pv@entry=0x20008af8) at FreeRTOS/Source/portable/MemMang/heap_4.c:268
268                     configASSERT( ( pxLink->xBlockSize & xBlockAllocatedBit ) != 0 );
(gdb) bt
#0  0x0800efbc in vPortFree (pv=pv@entry=0x20008af8) at FreeRTOS/Source/portable/MemMang/heap_4.c:268
#1  0x0800cd04 in serial_destroy (s=s@entry=0x20008af8) at ../../src/serial/serial.c:83
#2  0x0800d892 in process_new_connection (s=0x20008af8) at ../../src/tasks/wifi.c:389
#3  _task (params=<optimized out>) at ../../src/tasks/wifi.c:494
#4  0x0800ed00 in vPortEnterCritical () at FreeRTOS/Source/portable/GCC/ARM_CM3/port.c:367
#5  0xa5a5a5a4 in ?? ()
#6  0xa5a5a5a4 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Need to ensure that when we have too many connections we handle them with grace.

**Comment by stieg** [comment]
Fix Merged.
